on:
  push:
    branches:
    - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@main
        - name: Use Node.js 16.x
          uses: actions/setup-node@v2
          with:
            node-version: '16.18.1'
        - name: Install Dependencies
          run: npm install
