on:
  push:
    branches:
    - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@dev
        - name: Use Node.js 16.18.1
          uses: actions/setup-node@v2
          with:
            node-version: '16.18.1'
        - name: Install Dependencies
          run: npm install
        - name: Test
          run: npm lint
        - name: Build
          run: npm run build
        - name: Deploy
          uses: SamKirkland/FTP-Deploy-Action@3.1.1
          with:
            ftp-server: ${{ secrets.FTP_HOST }}
            ftp-username: ${{ secrets.FTP_USERNAME }}
            ftp-password: ${{ secrets.FTP_PASSWORD }}
            local-dir: ./
